export const GET_ALL_COUNTRY_DETAILS = 'GET_ALL_COUNTRY_DETAILS';
export const TOGGLE_SEARCH = 'TOGGLE_SEARCH';
export const SHOW_STATISTIC_PAGE = 'SHOW_STATISTIC_PAGE';
export const CHANGE_COUNTRY_DETAILS = 'CHANGE_COUNTRY_DETAILS';
export const CLEAR_SELECTED_COUNTRY = 'CLEAR_SELECTED_COUNTRY';
export const SELECT_COUNTRY = 'SELECT_COUNTRY';
